//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_CustomerProducts
    {
        public int Order_CustomerProductsID { get; set; }
        public int ProductID { get; set; }
        public int Order_CustomerAddressID { get; set; }
        public string Features { get; set; }
        public int Number { get; set; }
        public string ProductName { get; set; }
    
        public virtual Order_CustomerAddress Order_CustomerAddress { get; set; }
    }
}
